apiVersion: v2
name: keycloak-app
description: Wrapper chart for Keycloak with PostgreSQL and security best practices
type: application
version: 0.1.0
dependencies:
  - name: keycloak
    version: 22.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
