apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: election-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VotingM7011E/gitops.git
    targetRevision: main
    path: election-service
    helm:
      valueFiles:
        - ../environments/dev/election-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: election-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true