apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  serviceName: "postgresql-internal"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgresql-pvc
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: {{ .Values.postgresql.resources.requests.memory | quote }}
              cpu: {{ .Values.postgresql.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.postgresql.resources.limits.memory | quote }}
              cpu: {{ .Values.postgresql.resources.limits.cpu | quote }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.postgresql.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
