apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.serviceName }}
  labels:
    app: {{ .Values.mongodb.serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      name: mongodb
  selector:
    app: {{ .Values.mongodb.serviceName }}
