apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
  labels:
    app: {{ .Values.postgresql.serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.mongpostgresqlodb.port }}
      name: postgresql
  selector:
    app: {{ .Values.postgresql.serviceName }}
