apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
spec:
  selector:
    app: {{ .Values.app.name }}-frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
