apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-backend
spec:
  selector:
    app: {{ .Values.app.name }}-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
