---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    db-password: AgBl8+UadDLuoNG/ftdKobTZFId4+6XqN+tydoRx/UeDJ7XE2VEg6+NGUXgxElNfDq1JmRqNHYCHS1CRgdtQTBXgYl3SNHXyfoYPpgb+jd6I2GdSb/K+iJ046mjvhlK2Q5yZxZLxhvn63R1JMseN0PXJTquQJA4jUl4dw6ye1bvO3Qw0YIgJil2mI9ZqQwHwZX8E6rTJeSAOc5WNgAh2nTOJolXlsSgrJTTNiMQ3J8v0tDKMZj9B2WuHrT2wL+ooRD+abKIMopqmrMK1P3c3GhBNW+sfVhkzWR/v23frk7zpZnxsgZcVfiK9cKE/iha9HKPrQhOXsn5J8dGuIAiOdjnAPqnbU+BttiAlwvZ9042y1frvnxuVyUUPxeWdzbLUfGBMWv1W3WZkL/Pi9auetMGM65vouKpLcouYUxZ/OMURVFt06nVSU00yo4Bfs+z/Ghz2F8Ho0LM8QGPkSfdldAmh7Kq2V7lYXSvXbqIha6mEPQbrfEBI9U0o8v5RwX3lq+oeEHbXiUR7s0OsF4PPQdGtgHDkMoCrAPxREW+EclsuZQxHXVM3k7g06pjNmZ8+LQ4c9arOyP7yX4ehUaokAvFUn4g6XO6PUueHhj7s0SOYEDpsDjDA1HqWc1WyDfZ0CK5s5o/4yXjUzVlLXZ9O9HD2PkYM+2D/9SK0UCdOeCpwMg4xpv8KHSkgDXUbMWpYNVstaJkZ5zzF7BATn8gsE6RG
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
