---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgBmn0B2a2hkV4QBOFkLm4XHIFcVCjThY/IjTnrR1PJJjXZjUo+MFrT+Me9nItwQbQfigEs1dfBG8a7Pp5ek+uEtLO63MDiEx19ayQY8tAue2jrP9DMvXr2soskX+xJk4mmbqsdibs4IGZB8/aBzG+dZwvYkbrIXNJtzhNo5/4Arqw3vs0hyiOWGOk9ylJHivuQVBSO9q7CvZV12aqo0YVbtW2hrpcaOvutivl79V42p8szJTmmpn0pzrWwOPuoiuB6bhMC2WlK/UlCKu+YAdnJPeVyNBbkhO5pobep3Iy2UDNGv4fET7w2nMFzkKhZOvDTjEkGe3VFGG0reavDRQJpZsauZesp9RgCKjMGlGh+Z7hN2D2Y/iR2QZoZ2COEr+9IAxrCM6a5MKHhuzBFdQHQMl4QaaszGCA5YT9waC1GjT4Elr3zvaiMHPvjdD4Q7aLlXij/b9SqafB7Krm98O4g4CQxuRzA2f4qcPlA8nHnpb1nQv31DOi6UNkZfvJSuUtcS3a7VQZYd5ptI33DtAi69TQNXDQvn5QiOLWh2DB6RZUnsuRKfK/b1MwZlNd8UuSKCeC6Yf4NyOQaq5eitBy1iIDl/mYzNmfc4DzfZPmssRMIwsI0w7LXWsuj7eO1UoeoKudk2k+grfCgZECB1k353OPtjonRYQHll7uCEkt88DB4J5rDs05R/2p5yEE1z6XtMC5q48JEDiC5Z4b0CT40p
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
